from dotenv import load_dotenv
import os
#load_dotenv(".env.rex",override=True)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_DIR, ".env.rex"), override=True)

from langchain_core.tools import StructuredTool
from langchain_tavily import TavilySearch
from langgraph.prebuilt import ToolNode
from state import GraphState
from langchain_core.messages import AIMessage

from schemas import AnswerQuestion, ReviseAnswer

tavily_tool = TavilySearch(max_results=2)


# def run_queries(search_queries: list[str], **kwargs):
#     """Run the generated queries."""
#     return tavily_tool.batch([{"query": query} for query in search_queries])
#
#
# execute_tools = ToolNode(
#     [
#         StructuredTool.from_function(run_queries, name=AnswerQuestion.__name__),
#         StructuredTool.from_function(run_queries, name=ReviseAnswer.__name__),
#     ]
# )
def execute_tools_node(state: GraphState):
    """
    Execute the search queries generated by the LLM and
    store the raw search results in GraphState.
    """

    # Get the latest AI message
    last_ai_message = None

    for message in reversed(state["messages"]):
        if isinstance(message, AIMessage):
            last_ai_message = message
            break

    if last_ai_message is None:
        raise ValueError("No AIMessage found in state.")
    # Make sure there is a tool call
    if not last_ai_message.tool_calls:
        raise ValueError("No tool calls found.")

    # Extract the tool call
    tool_call = last_ai_message.tool_calls[0]

    # Get search queries
    search_queries = tool_call["args"]["search_queries"]

    # Execute Tavily searches
    results = tavily_tool.batch(
        [{"query": query} for query in search_queries]
    )
    # Save the raw results in GraphState
    return {
        "search_results": str(results)
    }